map $cookie_gel_skin $gel_scheme_id {
    default   "";
    atlas     21;   # Domino's Gambit
    terminal  22;   # Terminal
    stray     23;   # Stray
    dub       24;   # Dub
    prism     25;   # Prism
    laughing  26;   # Laughing
    ed        27;   # Ed
}