# GENERATED by scripts/brand/build_skins.py — do not hand-edit.
# Seeds/updates the Discourse colour palette for every skin manifest.
# Idempotent. Prints name => id so new palettes can be written back into
# their manifest's `# gel: palette-id` line (the nginx map needs it).
#
# user_selectable is REQUIRED: application_helper.rb#user_scheme_id ignores
# the color_scheme_id cookie for palettes without it, which silently kills
# the whole first-paint path.
SCHEMES = {
  "Domino's Gambit" => { "primary" => "d8d3c4", "secondary" => "0b0e14", "tertiary" => "e0a86f", "quaternary" => "6fd6e0", "header_background" => "0b0e14", "header_primary" => "d8d3c4", "highlight" => "e0a86f", "danger" => "e85555", "success" => "5fd38d", "love" => "e0a86f", "selected" => "11161f", "hover" => "182030", "primary-medium" => "8f8d82", "primary-low-mid" => "6b6f78" },
  "Terminal" => { "primary" => "e0e0e0", "secondary" => "1a1a1a", "tertiary" => "5fd38d", "quaternary" => "4a9d6d", "header_background" => "1a1a1a", "header_primary" => "e0e0e0", "highlight" => "5fd38d", "danger" => "e85555", "success" => "5fd38d", "love" => "5fd38d", "selected" => "2a2a2a", "hover" => "3a3a3a", "primary-medium" => "999999", "primary-low-mid" => "6b6f78" },
  "Stray" => { "primary" => "e6dde4", "secondary" => "0d0a12", "tertiary" => "ff3d9a", "quaternary" => "6fd6e0", "header_background" => "0d0a12", "header_primary" => "e6dde4", "highlight" => "ff3d9a", "danger" => "e85555", "success" => "5fd38d", "love" => "ff3d9a", "selected" => "16111c", "hover" => "201828", "primary-medium" => "8d8393", "primary-low-mid" => "6b6470" },
  "Dub" => { "primary" => "e8e0c8", "secondary" => "0e120c", "tertiary" => "f0c34e", "quaternary" => "3fae6a", "header_background" => "0e120c", "header_primary" => "e8e0c8", "highlight" => "f0c34e", "danger" => "e85555", "success" => "5fd38d", "love" => "e0433f", "selected" => "151b12", "hover" => "1e2818", "primary-medium" => "979274", "primary-low-mid" => "6f7563" },
  "Prism" => { "primary" => "dcdce4", "secondary" => "101014", "tertiary" => "9d7bff", "quaternary" => "4fd6d0", "header_background" => "101014", "header_primary" => "dcdce4", "highlight" => "9d7bff", "danger" => "e85555", "success" => "5fd38d", "love" => "9d7bff", "selected" => "17171e", "hover" => "20202a", "primary-medium" => "8f8f9c", "primary-low-mid" => "74747f" },
  "Laughing" => { "primary" => "e6eef7", "secondary" => "0a1018", "tertiary" => "56a8e8", "quaternary" => "7fd0e8", "header_background" => "0a1018", "header_primary" => "e6eef7", "highlight" => "56a8e8", "danger" => "e85555", "success" => "5fd38d", "love" => "56a8e8", "selected" => "101a26", "hover" => "182636", "primary-medium" => "8b98a8", "primary-low-mid" => "66727f" },
  "Ed" => { "primary" => "f2e7d4", "secondary" => "171008", "tertiary" => "ff8c3a", "quaternary" => "ffd23f", "header_background" => "171008", "header_primary" => "f2e7d4", "highlight" => "ff8c3a", "danger" => "e85555", "success" => "5fd38d", "love" => "ff8c3a", "selected" => "221809", "hover" => "2f2210", "primary-medium" => "a89478", "primary-low-mid" => "7d7057" },
}

SCHEMES.each do |name, colors|
  scheme = ColorScheme.find_by(name: name) || ColorScheme.new(name: name)
  colors.each do |cname, hex|
    existing = scheme.color_scheme_colors.find { |c| c.name == cname }
    if existing
      existing.hex = hex
    else
      scheme.color_scheme_colors << ColorSchemeColor.new(name: cname, hex: hex)
    end
  end
  scheme.user_selectable = true
  scheme.save!
  # mutated CHILD rows do not autosave with the parent — persisting the
  # scheme alone silently drops colour updates (creation works, update
  # no-ops; found when Dub's hearts stayed gold)
  scheme.color_scheme_colors.each(&:save!)
  scheme.touch
  puts "#{name} => #{scheme.id}"
end
