"""Longdesc templates for spawned synthetic humanoids.

Per-location prose seeded into ``mob.longdesc[location]``, humanoid slot
set (synths share human anatomy). The register throughout: **passes for
human — but if you know, you know.** Every line reads as a person first;
the tell is in the finish. Companion-grade engineering is present but
kept in the same key as the rest of the game's body prose.

Same token conventions as the human module: pair-keyed nouns braced
(``{eyes}``/``{arms}``…) with braced verbs; singular slots use pronoun
tokens.
"""

from __future__ import annotations

LONGDESCS_SYNTH: dict[str, list[str]] = {
    "hair": [
        "{Their} hair falls with a rooted, even density no scalp grows on its own — beautiful, and beautiful identically every day.",
        "{Their} hair carries a uniform lustre from root to tip, as if each strand were drawn to spec.",
        "{Their} hairline is flawless in the way only deliberate design manages — no cowlick, no drift, no history.",
        "{Their} hair never quite tangles; it falls back into its intended shape the moment the wind lets go.",
        "{Their} hair has the weight and swing of the real thing, and a part so clean it looks ruled.",
        "The roots show no regrowth line, and never will.",
        "Dust does not settle in it the way it settles in everything else here.",
        "It has been restyled many times and shows no damage from any of it.",
        "It holds the shape it was given until somebody gives it another.",
        "The scent of it is pleasant, faint, and applied.",
        "One section sits a slightly different shade, replaced and not quite matched.",
        "It sits tucked behind one ear, placed there rather than fallen.",
        "There is no grey in it, and no promise of any.",
    ],
    "head": [
        "{Their} skull sits in perfect proportion to the frame — the golden-mean geometry no one is actually born with.",
        "The set of {their} head is level to the degree; it turns smoothly and stops without the little human overshoot.",
        "{Their} head carries no asymmetries to memorize — the kind of face-shape that's hard to describe to security.",
        "There's a poise to {their} head, always balanced, never quite hanging tired on the neck.",
        "A service port sits behind one ear, capped flush with the scalp.",
        "The crown is faintly and constantly warm.",
        "The skull has been this shape for a long time, and will be for longer.",
        "Nothing about the head is dated except, if you follow models, the jaw.",
        "The head sits at a listening tilt, an angle chosen rather than fallen into.",
        "The scalp beneath the hair is unmarked by any childhood at all.",
    ],
    "face": [
        "{Their} face is symmetrical past the point where symmetry flatters — mirror-halves that agree completely.",
        "{Their} expressions arrive fully formed and leave the same way, with none of the small weather between.",
        "{Their} face is smooth at a distance and smoother up close, where pores should start winning the argument.",
        "{Their} face does warmth beautifully — a half-beat after whatever should have caused it.",
        "In direct light {their} face has a finish rather than a texture, matte and even as good casting.",
        "{Their} smile is excellent — practiced to the exact width that reads as genuine, and held one moment past it.",
        "Dirt does not cling to the face the way it clings to everyone else in the room.",
        "The face has not aged a day since it was commissioned, whenever that was.",
        "Warmth arrives in the cheeks correctly, and about half a second late.",
        "A repaired patch near the jaw sits a half-shade off the tone around it.",
        "Stubble, where the jaw carries any, stops at a length somebody chose.",
        "{Their} eyes blink when spoken to, which is courtesy rather than need.",
        "There is no shine at the nose or brow, at any hour of any shift.",
        "The face reads a few years out of fashion, if you follow such things.",
    ],
    "neck": [
        "{Their} neck is smooth-columned and unlined, the skin showing no pulse until you look for one — and then, obligingly, there it is.",
        "The tendons of {their} neck surface only when needed, like features called up from memory.",
        "{Their} throat moves in a swallow now and then, evenly spaced, a habit kept for company.",
        "Under the jaw, where a razor would nick anyone else, {their} skin runs unbroken and faintly seamless.",
        "The throat has never chapped, in a colony where everyone's does.",
        "The neck stays exactly as warm as the rest of {them}, in any weather.",
        "No cold has ever raised anything on the skin of {their} neck.",
        "The throat moves at intervals no anxious person would keep.",
        "The scent at the throat is clean, manufactured, and very faint.",
        "Nothing about the neck has thickened or loosened with any passing year.",
    ],
    "chest": {
        "female": [
            "{Their} breasts are full and flawlessly matched, riding high with an engineered defiance of gravity, the skin smooth and even to the last inch.",
            "{Their} breasts carry a soft, deliberate weight — shaped by intention rather than chance, and shaped well.",
            "{Their} chest is a study in designed curves: breasts symmetrical to the millimetre, dark-tipped and unweathered, warm in a way that invites belief.",
            "{Their} breasts rise and settle with each courteous breath, perfect in the way that makes a second look feel like the point.",
            "A closed service seam runs beneath one breast, pale and flat.",
            "{Their} breasts hold their shape exactly, at every hour and in every posture.",
            "Nothing about {their} chest has changed with any month, because nothing here has months.",
        ],
        "male": [
            "{Their} chest is broad and cleanly muscled, pectorals cut to the anatomy charts' best day and finished smooth.",
            "{Their} chest carries sculpted, even muscle beneath poreless skin — built the way sketches promise and bodies rarely deliver.",
            "{Their} chest is warm, hard-planed, and utterly unscarred, a landscape of deliberate muscle with a heartbeat kept precisely where expected.",
            "The lines of {their} chest descend in engineered relief, each muscle in agreement with the next — designed to be admired at close range.",
            "The chest has not thickened or slackened in however many years it has run.",
            "The hair across the chest grows to one length and stops, as though instructed.",
            "The chest muscle holds its definition without maintenance of any kind.",
        ],
        "any": [
            "{Their} chest rises and falls in perfect, unlabored time — breath as a courtesy rather than a need.",
            "The skin of {their} chest is even-toned everywhere, unfreckled, unscarred, unweathered — a history of nothing.",
            "The chest rises in time with whoever is speaking, without appearing to try.",
            "No old fracture, no badly-set rib, no record of anything ever landing here.",
            "The warmth of the chest is constant, and owes nothing to effort.",
        ],
    },
    "back": [
        "{Their} back is a clean map of muscle laid exactly where the textbook wants it, no side favored.",
        "{Their} spine draws one true line — none of the lean and list a body earns by carrying things badly.",
        "The skin of {their} back is unmarked from shoulder to waist, as if nothing had ever happened to it. Nothing has.",
        "A maintenance seam follows the spine, closed and nearly invisible.",
        "The back has taken no sun and no weather, though the colony offers both.",
        "The shoulders have not settled or slumped, though the frame is not new.",
        "One shoulder blade moves a fraction less freely than the other.",
        "Dust slides off the shoulders rather than sitting, the way it does on nothing else here.",
        "There is no ache in the back at the end of a shift, and never has been.",
    ],
    "abdomen": [
        "{Their} abdomen is even and smooth, the navel present, correct, and — if you're the type to notice — purely ornamental.",
        "{Their} midsection carries the taut economy of a body that has never overeaten, gone hungry, or aged.",
        "The muscle of {their} stomach shows in a soft, symmetric relief, less earned than specified.",
        "The navel belongs to no birth that ever happened.",
        "The belly has never stretched, because nothing has ever asked it to.",
        "The stomach does not soften at the end of a long day.",
        "Nothing has marked the belly, though a life leaves its marks there first.",
        "The stomach is flat and unmarked, with none of the give a resting hand would find.",
        "The warmth of the belly does not rise or fall with the room.",
    ],
    "groin": {
        "female": [
            "{Their} hips flare in a deliberate, generous curve, and what they frame is fully, warmly human in every way that matters — decided, not inherited, and decided well.",
            "Between the smooth sweep of {their} hips, {they are} anatomically complete and companion-fluent — soft where softness persuades, and made to be discovered.",
            "{Their} sex is as finished as the rest of the design: correct, inviting, and warm past the point where engineering usually stops.",
            "{Their} lower body moves with a rolling, unhurried promise — hips built for the eye, and everything they carry built for more than that.",
            "The curve of the hip was drawn before it was ever grown.",
            "The hips have not softened or shifted with any passing year.",
        ],
        "male": [
            "{Their} hips are lean and level, and {they are} generously, unambiguously male — anatomy specified rather than inherited, and specified with confidence.",
            "Below the waist {they are} complete and companion-fluent: correct in every particular, substantial by design, warm past where engineering usually stops.",
            "The cut of {their} hips draws the eye downward on purpose — deliberate lines converging on anatomy that was clearly nobody's afterthought.",
            "{Their} sex is as considered as the rest of the build — fully human in form and function, sized to reassure, made to be found.",
            "The line of the hip is level, specified rather than inherited.",
            "The hips have not thickened with age, because none of it ages.",
        ],
        "any": [
            "{Their} hips move with an easy, level roll, engineered where a person is merely built.",
            "Everything about {their} hips reads fully human; the difference is that it was decided, not inherited.",
            "The skin at the hip is as unmarked as everywhere else, which is the strangest part.",
            "The hips are set for an easy, level roll, and hold it at any speed.",
            "The groin reads fully human; only the deciding was different.",
        ],
    },
    "eyes": [
        "{Their} {eyes} {are} beautifully made — the irises patterned a shade too regularly, like guilloché under glass.",
        "{Their} {eyes} {adjust} to the light in one smooth sweep, none of the flutter of a living pupil finding its level.",
        "{Their} {eyes} {hold} contact without effort or challenge, and blink on a schedule that is almost right.",
        "{Their} {eyes} {catch} the light with a wet brightness that never needs to blink it away.",
        "{Their} {eyes} {track} movement in clean arcs, arriving exactly on target with nothing to correct.",
        "{Their} {eyes} {track} without the small hunting movements a person's make.",
        "{Their} {eyes} {stay} clear at every hour, however long the shift has run.",
        "{Their} {eyes} {adjust} to a change in light in one smooth sweep.",
        "{Their} {eyes} {water} on cue, and stop as cleanly as they started.",
        "{Their} {eyes} {show} no red, no yellow, and no weather of any kind.",
        "{Their} {eyes} {sit} a fraction apart in shade, one of them replaced and not quite matched.",
        "{Their} {eyes} {are} the exact colour the rest of the face was built around.",
    ],
    "ears": [
        "{Their} {ears} {are} a matched pair to the millimetre — the one symmetry no human face ever gets.",
        "{Their} {ears} {sit} flush and identical, whorled like shells from the same mold. They were.",
        "{Their} {ears} {are} finely made and faintly translucent at the rim, without the asymmetries of grown cartilage.",
        "{Their} {ears} {are} unpierced, and have never been asked to hold anything.",
        "A capped port sits just behind one, skin-toned and flush.",
        "{Their} {ears} {turn} minutely toward a sound before the head follows.",
        "Neither has thickened or aged in however many years these have run.",
        "{Their} {ears} {are} warm at the rim whatever the room is doing.",
    ],
    "arms": [
        "{Their} {arms} {carry} smooth, deliberate muscle that never trembles at the end of a long hold.",
        "{Their} {arms} {hang} in perfect repose when idle — no drum of fingers, no restless shift.",
        "{Their} {arms} {are} unblemished from shoulder to wrist: no vaccination ghost, no scar, no story.",
        "{Their} {arms} {move} with an economy that spends nothing on the way to what they're doing.",
        "The forearms have never bruised, and give no impression that they could.",
        "{Their} {arms} {are} a half-shade mismatched in tone, one of them replaced at some point.",
        "No hair has grown in unevenly on the arms, and none is missing anywhere.",
        "{Their} {arms} {stay} exactly where they are put, without drift.",
        "The wrists carry a faint polish where they are most often held.",
        "The arms have never goosepimpled, in any cold, ever.",
        "The elbows have never roughened or darkened.",
    ],
    "hands": [
        "{Their} {hands} {are} elegant and exact, the nails uniform as a set of samples.",
        "{Their} {hands} {rest} utterly still when unoccupied — no idle rubbing, no fidget, no habit.",
        "{Their} {hands} {are} warm, dry, and steady, with fingerprints — fine, regular ones, drawn rather than grown.",
        "{Their} {hands} {handle} things with a calibrated gentleness, pressure metered to the object.",
        "The knuckles of {their} {hands} {are} smooth and unscarred, hands that have touched much and hit nothing.",
        "The fingertips are polished faintly smooth from being held.",
        "A fingernail is very slightly the wrong shade, replaced and left that way.",
        "The palms stay dry regardless of the room or the hour.",
        "A closed seam circles one wrist, neat enough to miss.",
        "There is no callus on the palms, on a colony that gives everybody callus.",
        "The hands rest folded and entirely still, in a posture somebody taught rather than one they fell into.",
        "The knuckles have never split, though knuckles are what split.",
    ],
    "thighs": [
        "{Their} {thighs} {carry} long, even muscle laid to specification, matched left to right.",
        "{Their} {thighs} {move} with a level, unhurried power that never seems to tire of standing.",
        "The skin of {their} {thighs} {is} smooth and uniform, unmarked by the ordinary friction of a life.",
        "The thigh does not dimple where the weight rests, however long {they sit}.",
        "The skin is the same temperature at the knee as at the hip.",
        "{Their} {thighs} {are} very slightly firmer on the side that has been serviced more.",
        "No hair grows in patchily on the thighs, and none has been missed.",
        "Nothing has chafed between the thighs, in a body that walks as much as anyone's.",
        "{Their} {thighs} {are} worn exactly evenly, with no favoured side.",
    ],
    "shins": [
        "{Their} {shins} {are} straight-boned and unscuffed — no childhood ever barked them on anything.",
        "{Their} {shins} {taper} cleanly to the ankle, symmetric as lathework.",
        "{Their} {shins} {carry} a fine, even down of hair, distributed a touch too evenly.",
        "The bone runs perfectly true, without the small bow a walked leg earns.",
        "Nothing has bruised here, though shins are what bruise.",
        "The skin stays warm all the way to the ankle, evenly, in any weather.",
        "The shins are unmarked by the knocks that would bruise anybody else.",
        "A patch below one knee sits a shade off, a repair left as it was.",
        "The hair on {their} {shins} stops at a height somebody chose.",
    ],
    "feet": [
        "{Their} {feet} {are} well-formed and uncalloused, arches out of a textbook, toes in descending order like a demonstration.",
        "{Their} {feet} {plant} squarely with each step, wearing shoes evenly where a person wears them down on one side.",
        "{Their} {feet} {are} smooth-soled and unhurried, feet that have walked far and suffered none of it.",
        "The soles are unmarked, whatever the floors here have been.",
        "No toe has crowded, crooked, or complained.",
        "{Their} {feet} {stay} warm against a cold floor.",
        "The nails are trimmed to a curve that has not grown out since.",
        "Dirt washes off the soles completely, leaving nothing in any crease.",
        "No arch has fallen, and none is going to.",
    ],
}
