"""Longdesc templates for spawned robots.

Per-location prose seeded into ``mob.longdesc[location]``. Same token
conventions as the human module:

* Pair-keyed nouns wrapped in braces (``{eyes}`` / ``{ears}`` /
  ``{arms}`` / ``{hands}`` / ``{thighs}`` / ``{shins}`` / ``{feet}``) so
  the renderer can flex them when one side collapses, with braced verbs
  whose subject is that paired noun.
* Singular locations (``head``, ``face``, ``chest`` ...) use plain prose
  with pronoun tokens.

Slot keys mirror the humanoid set in ``world/anatomy/species.py`` — a
robot is a humanoid chassis, so it uses the human ``pair_keys`` /
``default_longdesc_locations`` (no ``hair`` slot — robots are unhaired,
so that slot stays unseeded).
"""

from __future__ import annotations

LONGDESCS_ROBOT: dict[str, list[str]] = {
    # Head region
    "head": [
        "{Their} head is a smooth alloy casing, seams running clean along the jaw and crown.",
        "{Their} cranial housing is dented above one temple, the impact sealed with a rough weld.",
        "A cluster of sensor ports rings the back of {their} skull, dark glass set flush with the plating.",
        "{Their} head pivots on an exposed servo collar, the joint hissing faintly with each turn.",
        "The crown of {their} head carries a faded designation stencil, half-scrubbed to bare metal.",
        "A previous owner's paint has flaked from {their} skull casing, leaving grey alloy beneath.",
        "{Their} head casing is mismatched to the neck, a salvaged unit bolted on and left unpainted.",
        "Dust has settled into the seams of {their} cranial plating, tracing every panel line grey.",
        "Someone has drilled a fresh mounting point into {their} skull and left the hole unused.",
        "The left side of {their} head plating sits proud of the right, a repair never quite squared.",
        "A coolant line loops over {their} crown and down behind, clipped with salvaged brackets.",
        "Scorch marks fan back from {their} brow plate, the alloy blued by whatever burned there.",
        "{Their} head housing carries a stamped serial plate, the digits worn shallow by handling.",
    ],
    "face": [
        "{Their} face is a fixed sculpted plate, expressionless but for the glow of an optical band.",
        "A horizontal sensor strip crosses {their} face where eyes would sit, lit a steady amber.",
        "{Their} faceplate is scuffed and micro-scratched, the finish gone matte from years of grit.",
        "Twin grilles flank a blank central plate, venting the faint warmth of internal processors.",
        "{Their} face is featureless armor, the only motion the slow refocus of recessed lenses.",
        "{Their} faceplate has been replaced at least once, the new alloy a shade brighter than the rest.",
        "A hairline crack runs from {their} left cheek plate to the jawline, sealed with clear resin.",
        "Someone has scratched a tally of marks into {their} faceplate, shallow and deliberate.",
        "{Their} face carries a dead indicator lamp above the vents, its lens gone smoke-grey.",
        "Grit has packed the vents across {their} lower face, dulling the airflow to a whisper.",
        "The paint on {their} faceplate is worn away in a broad band where a strap once rode.",
        "{Their} faceplate is bolted at four corners, the fasteners rounded off from repeated removal.",
        "A rough weld crosses {their} brow where a punctured plate was patched from the inside.",
    ],
    "neck": [
        "{Their} neck is a stacked column of articulated rings, cabling visible between the segments.",
        "Thick coolant lines run the length of {their} neck, ticking faintly as fluid cycles through.",
        "{Their} neck joint rotates with a low servo whine, exposing a band of bare actuator beneath.",
        "Coolant weeps from a fitting at the base of {their} neck, leaving a pale crust on the plate.",
        "{Their} neck column is wrapped in salvaged loom tape, the adhesive gone brown with heat.",
        "A hose clamp sits crooked on {their} neck line, tightened by hand and never straightened.",
        "Rust has crept into the ring seams of {their} neck, orange in every articulation gap.",
        "{Their} neck servo grinds on the third rotation, a fault nobody has bothered to bench.",
        "Someone has cable-tied a loose conduit against {their} neck to keep it clear of the joint.",
        "The plating at {their} throat is worn to a bright polish where the head housing rubs.",
        "A stress fracture runs across one of {their} neck rings, arrested by a drilled stop-hole.",
    ],

    # Torso region
    "chest": [
        "{Their} chest is a broad armored plastron, a recessed access panel set over the core.",
        "Status indicators glow in a row across {their} chest, pulsing in slow sequence.",
        "{Their} chest plating is scorched along one edge, the alloy discoloured by old heat.",
        "A faint reciprocating hum comes from deep in {their} chest where the power core sits.",
        "{Their} chest panel is held shut with a single mismatched bolt, the other three missing.",
        "Impact denting spreads across {their} plastron, the alloy pushed inward around a bright scar.",
        "A stencilled hazard triangle has half-peeled from {their} chest, the adhesive edges curling.",
        "Someone has ground a serial number off {their} chest plate and never stamped a new one.",
        "{Their} chest vents tick as they cycle, exhaling warm air that smells faintly of hot oil.",
        "Weld spatter freckles the lower edge of {their} chest plating, never dressed back smooth.",
        "A cracked indicator lens on {their} chest glows dimmer than the others in the row.",
        "The armor over {their} core is doubled with a bolted-on salvage plate, crude but honest.",
    ],
    "back": [
        "{Their} back is a ridged heat-sink array, shedding a thin shimmer of warm air.",
        "Cable runs and conduit trace {their} spine beneath a hinged maintenance panel.",
        "{Their} back plating is gouged and re-welded, the repairs left honestly visible.",
        "{Their} heat-sink fins are bent flat in one corner, the airflow forced around the damage.",
        "Grime has collected in the fin gaps down {their} back, packed hard by heat and time.",
        "A maintenance panel on {their} back hangs from one hinge, the other sheared clean off.",
        "Weld beads climb {their} spine in a rough ladder, each one a different hand's work.",
        "Someone has stencilled a lift point on {their} upper back, the paint chipped by hook wear.",
        "{Their} back plating rings hollow where a section was replaced with thinner salvage stock.",
        "Coolant staining runs down {their} back from a fitting that has leaked and been retightened.",
        "The fin array across {their} shoulders is scorched black at the centre, bright at the edges.",
    ],
    "abdomen": [
        "{Their} midsection is a flexible segmented band, articulating as the frame bends.",
        "An exposed actuator bundle works at {their} waist, hissing softly with each motion.",
        "{Their} abdominal plating is patched with mismatched alloy, salvaged and bolted in place.",
        "{Their} midsection bellows-plating is split at one fold, the tear stitched shut with wire.",
        "Hydraulic lines cross {their} belly in a loose bundle, chafed where they rub the frame.",
        "A dented access hatch sits low on {their} abdomen, the latch replaced with a bent pin.",
        "Grit has worked into the segment gaps of {their} waist, grinding audibly as the frame bends.",
        "{Their} abdominal shell carries a puncture the size of a thumb, plugged and welded over.",
        "Someone has run a strap anchor through {their} midsection plating, drilled rough and unpainted.",
        "The flex band at {their} waist is worn shiny across the front, matte everywhere else.",
        "Oil has crept from a seam in {their} abdomen and dried in a long dark streak downward.",
    ],
    "groin": [
        "{Their} hip assembly is a heavy articulated joint, the servos broad and exposed.",
        "Hydraulic lines converge at {their} pelvis, the fittings beaded with old fluid.",
        "{Their} pelvic assembly is caked with dried lubricant, the grit of the street set into it.",
        "A hydraulic fitting at {their} hip has been replaced with a mismatched brass union.",
        "Load-bearing brackets bolt across {their} pelvis, added later and never blended in.",
        "{Their} hip servos sit exposed in their cradle, the housings scarred from ground strikes.",
        "Someone has wrapped a weeping line at {their} groin in tape, a repair that clearly holds.",
        "The plating over {their} pelvic joint is scraped bright along one edge from hard contact.",
        "Coolant lines loop tight around {their} hip cradle, clipped with fittings of three makes.",
        "Rust blooms in the seams of {their} pelvic housing where fluid has sat and dried again.",
    ],

    # Arms
    "eyes": [
        "{Their} {eyes} {are} a pair of recessed optical lenses, refocusing with faint mechanical clicks.",
        "{Their} {eyes} {glow} a steady amber, the apertures contracting as they track movement.",
        "{Their} {eyes} {sit} behind scratched protective glass, whirring softly as they adjust.",
        "{Their} {eyes} {are} cold pinpoints of sensor light, unblinking and always moving.",
        "{Their} {eyes} {carry} a faint flicker at the edges — a processor reading the whole room at once.",
        "{Their} {eyes} {sit} deep in scarred bezels, the housings scratched down to raw alloy.",
        "Hairline cracks web the outer glass of {their} {eyes}, catching the light at odd angles.",
        "Someone has re-seated {their} {eyes} badly, leaving a thin gap around the housing.",
        "{Their} {eyes} {dim} whenever the frame draws hard, then {return} to full brightness.",
        "Grit has scoured the metal around {their} {eyes}, dulling the finish to a flat grey.",
        "{Their} {eyes} {track} with a half-second lag, the aiming servos worn out of true.",
        "A jammed protective shutter sits half-drawn across {their} {eyes} and stays that way.",
        "Dust films the lens glass of {their} {eyes}, the light behind it steady all the same.",
    ],
    "ears": [
        "{Their} {ears} {are} flush audio grilles set where a person's would be, swiveling minutely toward sound.",
        "{Their} {ears} {are} fine mesh intakes, filtering the room's noise into something the processor can parse.",
        "{Their} {ears} {sit} as dark recessed ports, attentive to every shift in the ambient hum.",
        "{Their} {ears} {are} paired pickups behind perforated plates, tracking the faintest sound.",
        "{Their} {ears} {are} clogged with fine grey dust, the mesh long overdue for a purge.",
        "A mesh screen over {their} {ears} has torn open, the pickup behind it bare to the air.",
        "Someone has bolted a coarse guard across {their} {ears}, crude but effective against grit.",
        "{Their} {ears} {swivel} a few degrees toward every sound, the motion small and constant.",
        "Corrosion has spread around the port rims of {their} {ears}, green at the fastener heads.",
        "The plating around {their} {ears} is dented inward, narrowing the intakes without closing them.",
        "{Their} {ears} {sit} flush with the skull plating, betrayed by a faint perforated pattern.",
        "Weather has stained the mesh of {their} {ears} a streaked brown that no cleaning lifts.",
    ],
    "arms": [
        "{Their} {arms} {are} segmented actuator assemblies, cabling visible at every joint.",
        "{Their} {arms} {move} with a smooth servo-driven precision, never quite silent.",
        "{Their} {arms} {are} armored and scuffed, the plating gouged from heavy use.",
        "{Their} {arms} {hang} loose at {their} sides, the elbow servos ticking as they idle.",
        "{Their} {arms} {carry} mismatched plating, one clearly a salvaged replacement.",
        "{Their} {arms} {end} in reinforced wrist collars, bright where a tool coupler locks on.",
        "Chafe marks band {their} {arms} where the cabling has rubbed the plating for years.",
        "{Their} {arms} {hiss} at the shoulder with every lift, a seal that no longer seats clean.",
        "Someone has stencilled a load rating onto {their} {arms}, half of it scraped away since.",
        "{Their} {arms} {are} plated in overlapping scales that grind faintly as the joints work.",
        "Grease has blackened the elbow seams of {their} {arms}, worked in past any cleaning.",
        "Deep parallel gouges score {their} {arms}, the metal curled up at the edge of each cut.",
        "Stripped fasteners ring the access panels on {their} {arms}, forced open more than once.",
    ],
    "hands": [
        "{Their} {hands} {are} three-fingered manipulators, the digits ending in worn grip pads.",
        "{Their} {hands} {flex} with a faint servo whine, each joint articulating independently.",
        "{Their} {hands} {are} heavy alloy graspers, scratched bright at the fingertips.",
        "{Their} {hands} {carry} the scuffs of constant work, the grip surfaces polished smooth.",
        "{Their} {hands} {close} with deliberate mechanical care, precise and unhurried.",
        "{Their} {hands} {are} short one fingertip pad, the bare actuator tip still working fine.",
        "Solvent has stripped the finish from {their} {hands}, leaving the alloy dull and porous.",
        "Someone has wound grip tape around the palms of {their} {hands}, worn through in patches.",
        "{Their} {hands} {twitch} through a calibration cycle now and then, fingers counting off in order.",
        "Scorch discolours the fingertips of {their} {hands}, blued from handling hot work.",
        "A knuckle joint on {their} {hands} sits swollen with a replacement pin, oversized and proud.",
        "{Their} {hands} {carry} a builder's grime in every seam, black and long since permanent.",
        "Wear has polished the thumb pads of {their} {hands} to a mirror, the rest left matte.",
    ],

    # Legs
    "thighs": [
        "{Their} {thighs} {are} broad hydraulic struts, the pistons filmed with a sheen of fluid.",
        "{Their} {thighs} {are} armored load-bearing members, dented along the leading edge.",
        "{Their} {thighs} {flex} with a deep hydraulic sigh as the frame shifts its weight.",
        "{Their} {thighs} {carry} thick bundled cabling beneath scuffed protective plating.",
        "{Their} {thighs} {weep} a slow film of hydraulic fluid, the plating streaked dark below.",
        "Ground strikes have chewed the outer plating of {their} {thighs} back to bare alloy.",
        "{Their} {thighs} {are} cross-braced with bolted salvage stock, stiffened after a break.",
        "Dust cakes the piston shafts of {their} {thighs}, scoring the polish as they slide.",
        "Someone has zip-tied a chafed line flat against {their} {thighs} to keep it off the joint.",
        "{Their} {thighs} {shudder} faintly under load, a hydraulic knock that never quite clears.",
        "The armor down {their} {thighs} is scratched in long runs from squeezing past steel.",
        "Heat has blistered the paint along {their} {thighs}, curling it up in brittle grey flakes.",
    ],
    "shins": [
        "{Their} {shins} {are} reinforced strut housings, scarred and scraped from rough ground.",
        "{Their} {shins} {are} bare actuator columns, the servos exposed and ticking.",
        "{Their} {shins} {carry} mismatched plating, one panel clearly a field repair.",
        "{Their} {shins} {are} caked with grime along the lower joints, the alloy showing through.",
        "{Their} {shins} {take} the worst of the street, dented and scraped from ankle to knee.",
        "Rust rings the fastener heads down {their} {shins} where the coating has chipped away.",
        "A bent guard plate on {their} {shins} has been hammered roughly back toward flat.",
        "{Their} {shins} {rattle} slightly at speed, a loose panel nobody has bothered to shim.",
        "Splashed grime dries in tidelines along {their} {shins}, each layer a little darker.",
        "Someone has drilled drain holes low in {their} {shins}, crude but keeping them dry.",
        "{Their} {shins} {are} pitted with corrosion along the lower quarter, the alloy gone chalky.",
        "Weld slag beads the seam down {their} {shins}, never ground back after the repair.",
    ],
    "feet": [
        "{Their} {feet} {are} broad splayed stabilizers, the soles worn smooth and bright.",
        "{Their} {feet} {are} heavy magnetic pads, clicking faintly against the floor.",
        "{Their} {feet} {carry} the dents of hard use, the toe plates scraped to bare metal.",
        "{Their} {feet} {plant} with a solid mechanical certainty, distributing the frame's mass.",
        "{Their} {feet} {ring} against hard flooring, each step announcing the frame's weight.",
        "Grit has jammed the toe articulation of {their} {feet}, stiffening the roll of each step.",
        "{Their} {feet} {carry} bolted-on wear plates, the fasteners countersunk and blunted flat.",
        "Corrosion creeps up from the sole seams of {their} {feet}, orange against grey alloy.",
        "Someone has re-shimmed the ankle joints of {their} {feet} with washers of three thicknesses.",
        "{Their} {feet} {leave} a faint oil print on dry ground, thin and quickly gone.",
        "The heel plates on {their} {feet} are worn to a wedge, the frame leaning back to compensate.",
        "Deep scoring crosses the soles of {their} {feet}, cut by rough ground and heavy loads.",
    ],
}
