"""Longdesc templates for randomly-spawned mobs, keyed by anatomy slot.

Two kinds of keys:

* Singular locations (``hair``, ``head``, ``face``, ``neck``, ``chest``,
  ``back``, ``abdomen``, ``groin``) — applied to that one location.
* Pair keys from ``PAIR_MERGE_KEYS`` (``eyes``, ``ears``, ``arms``,
  ``hands``, ``thighs``, ``shins``, ``feet``) — one entry is applied to
  *both* sides, so the renderer's paired-collapse path engages and the two
  sides render as a single plural line.

Token conventions:

* Pronouns: ``{their}`` / ``{they}`` / ``{them}`` / ``{themselves}`` and
  their capitalized variants resolve to the apparent gender at render time.
* Pair-slot nouns: brace ``{eyes}`` / ``{ears}`` / ``{arms}`` / ``{hands}``
  / ``{thighs}`` / ``{shins}`` / ``{feet}`` so the renderer can singularize
  them if one side is lost. Any verb that must agree should also be braced
  (``{are}``, ``{move}``) — its plural form is authored, the renderer
  conjugates the singular when needed.

Add entries by appending to the relevant list; no registration step.
"""

from __future__ import annotations

LONGDESCS: dict[str, list[str]] = {
    # =====================================================================
    # HEAD REGION — singular locations
    # =====================================================================
    "hair": [
        "It hangs in {their} face in uneven strands that {they keep} not bothering to brush back.",
        "It is cropped close enough to suggest a recent decision rather than a style.",
        "It looks like it was last cut by {themselves}, in poor light, in a hurry.",
        "It carries the faint flat sheen of cheap colony shampoo.",
        "It is dry at the ends and oily at the roots, the kind of hair that resists conditioning.",
        "Stray flakes of something pale catch the light here and there.",
        "It is tied back functionally, the way a person ties hair back when they expect to be moving.",
        "The roots show a centimeter of a different color, telling on a recent cosmetic decision.",
        "It hangs limp around {their} ears, neither tidy nor a statement.",
        "There's a half-healed scrape visible along the scalp where the hairline gives way.",
        "A faint ring of static makes the shorter hairs stand on end.",
        "It is pulled tight against the skull, severe in a way that does the face no favors.",
        "One side is noticeably shorter than the other, as if {they} fell asleep on a fire.",
        "It is greying in a streak that suggests stress, not age.",
        "It has the slightly mineral stiffness that comes from washing in recycled water.",
        "A few strands have caught at the nape of {their} neck and stayed there.",
        "It has been combed exactly once today and not since.",
        "The colony's overhead lights pick out every individual strand unkindly.",
        "It frames {their} face in a way that seems deliberate and unflattering.",
        "It bears the dull cast of hair that has spent too many hours under unfiltered air.",
        "It bears the faint indentation of a hat that is no longer being worn.",
        "There's a streak of dust through it that {they have} not noticed yet.",
        "It is parted unevenly, as though by accident, and never corrected.",
        "It has the slightly brittle look of hair that has met too many chemicals.",
        "Wisps of it move when {they move}, never quite settling.",
        "It is gathered at the nape in a knot tied without ceremony.",
        "It looks slept-in, in a way that suggests {they} slept somewhere harder than a bed.",
        "There's a single piece of grit caught in it that catches the light.",
        "The colony's filtered air has done it no favors.",
        "It is thick enough at the temples to hide whatever {their} ears are doing.",
        "It clings to the back of {their} neck where sweat has dampened it.",
        "It has the unevenness of hair that's been growing out from something shorter.",
        "It falls forward whenever {they look} down and {they keep} pushing it back.",
        "It hangs in a slightly tangled coil at the nape that someone smoothed back hours ago.",
        "A few short hairs stick up at the crown in a permanent cowlick.",
        "It is matted in one small patch where something dried into it and was not fully washed out.",
        "It is braided in a tight, no-nonsense pattern that suggests practical concerns.",
        "There's a small piece of plastic — a clip, maybe — barely holding part of it in place.",
        "It is dusted lightly with what looks like ash, or just colony dust.",
        "It has the flat, freshly-shaved feel of having been buzzed down within the last day.",
        "It is fine and thin enough that the scalp shows through under the light.",
        "It hangs down past {their} jaw with no clear intention.",
    ],
    "head": [
        "{Their} head sits on {their} neck at a slight, considering angle.",
        "{Their} scalp shows the faint outline of an old impact scar above the temple.",
        "A small bald patch sits at the crown that looks accidental rather than chosen.",
        "The shape of {their} skull is plain under the skin, narrow and angular.",
        "A pale crescent scar runs along one side, neat enough to suggest medical work.",
        "{Their} head is held very still, as though motion costs something.",
        "There's a faint dent above one ear that nobody has ever explained to {them}.",
        "{Their} scalp glistens slightly with sweat that has nowhere to go.",
        "The skin at {their} temple twitches faintly with a slow, unconscious pulse.",
        "{Their} head turns in small, careful increments, as though tracking sound.",
        "A flat, smooth area at the back of the skull suggests a healed surgical access.",
        "{Their} forehead carries the etched horizontal lines of someone who frowns more than they smile.",
        "{Their} skull has the slightly heavy set of someone whose helmet has been worn too long, too often.",
        "There's a thin scar along the hairline that someone took the trouble to sew well.",
        "The crown of {their} head bears a faint, deliberate-looking implant access port.",
        "{Their} head tilts when {they listen}, as if one ear works better than the other.",
        "A small, faded data port sits flush behind one ear.",
        "{Their} head moves a beat after the rest of {them}, as if running on slight delay.",
        "There's a bruise just at the hairline, healing yellow-green.",
        "The cant of {their} head is slightly off vertical, in a way that suggests an old neck injury.",
        "A pale band of skin at the brow tells of safety glasses that were worn for years.",
        "{Their} head holds steady, eyes moving instead — the discipline of someone who's been trained.",
        "A faint indentation circles {their} crown where something tight used to be.",
        "{Their} skull narrows toward the back in a way the light catches.",
        "The skin across {their} forehead is dry, faintly flaking.",
        "{Their} head sits on {their} shoulders like it has been deliberately balanced.",
        "There's a healed laceration above one eyebrow that did not close well.",
        "{Their} scalp is faintly oily where the hair parts.",
        "A small irregularity at the temple suggests something is implanted just under the skin.",
        "{Their} head jerks faintly at small sounds, then catches itself.",
        "An old burn scar fans across the side of {their} head, hairless and pink.",
        "The base of {their} skull bears the faint shadow of a tattoo that's been laser-faded.",
        "{Their} head sits forward of {their} shoulders, as though leaning toward something to hear.",
        "{Their} crown is flat in profile, the shape that long sleep on hard surfaces produces.",
        "A streak of pale skin runs from temple to ear, the legacy of a long-healed cut.",
        "{Their} head has the heaviness of someone fighting a low-grade hangover.",
        "{Their} head is shaved in a single careful strip down the center of the scalp.",
        "There's a small dark birthmark at the temple, irregular and old.",
        "{Their} skull is faintly asymmetric, one side broader than the other.",
        "{Their} head rests at the precarious angle of someone almost falling asleep where they stand.",
        "A small electrode-shaped pale spot sits behind one ear, an old diagnostic mark.",
    ],
    "face": [
        "{Their} face wears the slack neutrality of someone who has stopped performing expressions.",
        ("slight", "{Their} cheeks are hollowed in a way that splits the difference between sculpted and underfed."),
        "A faded scar runs along {their} jawline, the kind that takes a season to lose its color.",
        "{Their} face is unevenly tanned, as though {they wear} something across half of it most days.",
        "There's a sheen of dried sweat on {their} brow that {they have} not yet wiped.",
        "{Their} mouth sits in a permanent, faint frown that does not seem to involve emotion.",
        "{Their} jaw is set in the way that people who grind their teeth set their jaws.",
        "{Their} cheekbones are high enough to put faint shadows under them in the colony lighting.",
        "A small, pale freckle sits near the corner of {their} mouth — the kind of mark people notice.",
        "{Their} face shows the lines of someone who has spent significant time squinting into wind.",
        "{Their} lips are dry and slightly cracked in two parallel lines.",
        "{Their} chin is shadowed with the early stubble of someone who shaved a day or two ago.",
        "There's a faint discoloration high on one cheek that might be a healing bruise.",
        "{Their} face holds the unreadable, watchful stillness of someone who has learned not to be read.",
        "{Their} mouth twitches at the corners, as though biting back something every few seconds.",
        "A faded thin scar bisects {their} upper lip, neat enough to be cosmetic if intentional.",
        "{Their} cheeks bear the faint pitting of skin that healed badly from an old illness.",
        "{Their} jaw works slowly, as though chewing on the word {they are} about to say.",
        "{Their} skin has the matte texture of someone who has stopped caring about moisturizer.",
        "A thin film of grime traces the line of {their} hairline, never quite scrubbed away.",
        "{Their} brow stays slightly furrowed, as though everything requires a small effort of concentration.",
        "{Their} face turns slowly toward whoever speaks, never quite first.",
        "There's a healed split in one eyebrow where the hair grows around a thin pale line.",
        "{Their} cheeks are flushed faintly red, in patches that suggest cold or alcohol.",
        "{Their} face wears the pale, slightly sweaty cast of someone fighting an illness {they have} not named.",
        "A long-faded tattoo curves along {their} jaw, illegible at this distance.",
        "{Their} expression sits between resignation and stubbornness, the look that gets a person through a long shift.",
        "{Their} face is freshly washed but not freshly rested — the cleanness is recent and superficial.",
        "{Their} cheeks bear the linear imprint of a recent nap against a rough surface.",
        "{Their} mouth holds a slight, ironic curve that does not quite become a smile.",
        "{Their} face moves in single units — eyes, then mouth, then jaw — never all at once.",
        "{Their} skin is flushed unevenly along one side of the jaw, the asymmetric pattern of poor circulation.",
        "There's a constellation of small old acne scars along one cheek.",
        "{Their} face wears the faintly waxen cast of someone who hasn't seen direct sun in a while.",
        "{Their} expression does not change when others speak, the way a person waits out a stranger's pitch.",
        "{Their} jaw is faintly slack on one side, the legacy of an injury or a tic.",
        "{Their} mouth holds the shape of words {they are} not speaking.",
        "A dark mole sits just under {their} eye, drawing attention by holding still.",
        "{Their} cheeks suck in slightly when {they concentrate}, hollowing further.",
        "There's a faint dusting of pale stubble across the jaw that catches the colony light.",
        "{Their} face has the unwashed sheen that comes from long hours under recycled air.",
        "{Their} mouth has the corners-down set of someone trying not to comment.",
    ],
    "neck": [
        "{Their} neck shows the faint horizontal line of a collar worn daily for years.",
        "A small, faded data port sits low on the side of {their} neck.",
        "The cords of {their} neck stand out faintly when {they swallow}.",
        ("slight", "{Their} neck is long enough to be noticed, narrow enough to look fragile."),
        "There's a healed scar curving around the throat, the kind nobody wants to ask about.",
        "{Their} pulse is visible at the side of the throat, ticking slightly fast.",
        "A small dark tattoo — letters, or numbers — sits at the base of {their} neck.",
        "The skin under {their} jaw is loose enough to soften the line of the throat.",
        "{Their} neck bears a faint ring of dirt low at the throat that no recent washing has caught.",
        "There's a discoloration low on the throat that might be a bruise or a birthmark.",
        "{Their} neck is corded with the tension of someone who has not relaxed their shoulders in hours.",
        "{Their} neck bears a long faded scar that runs from behind the jaw to the collarbone.",
        "{Their} neck is sunburned in an irregular patch, the work of one bad day off-dome.",
        "{Their} throat moves visibly when {they listen}, swallowing too often.",
        "There's a small dark mole high on the throat that catches the light.",
        "{Their} neck is unusually thick at the base, the build of a wrestler or a yoke worker.",
        "{Their} carotid pulse is faintly visible, the slow rhythm of someone steady.",
        "A faded surgical line runs across the front of {their} throat, healed pale.",
        "{Their} neck is held stiffly, as if turning hurts.",
        "There's a faint indentation low on the throat where a fingertip would rest.",
        "{Their} neck tenses visibly every time {they hear} a sudden sound.",
        "A pale scar runs from behind one ear down the side of {their} throat.",
        "{Their} neck is freckled where it meets {their} collarbones, sun damage from years ago.",
        "The skin of {their} neck is flushed faintly red, as if {they have} been recently exerting {themselves}.",
        "{Their} throat moves through a slow, deliberate swallow as {they settle} their breath.",
        "There's a small mole at the side of {their} throat that catches the eye.",
        "{Their} neck looks strangely vulnerable, the sleeve's only unarmored part.",
        "{Their} neck bears the round mark of something that used to be pressed there habitually.",
        "{Their} throat carries a long pale scar that runs across the side, healed years ago.",
        "A small, dark birthmark sits low under one ear in an irregular shape.",
        "{Their} neck bears the long-faded outline of a tattoo that's been laser-treated nearly invisible.",
        "There's a faint asymmetry to {their} neck, one side fuller than the other.",
        "{Their} throat carries the loose set of a person who rarely tenses their jaw.",
        "{Their} neck holds the stillness of someone listening hard.",
        "A pale white scar circles {their} throat horizontally, neat as a line on a page.",
        "{Their} neck is dotted with faint, healed insect bites — colony fauna at work.",
        "{Their} throat bears a small, intentional brand low at the side, deliberate and old.",
        "There's a healed puncture scar low on the side of the neck, the kind that does not announce itself.",
        "{Their} neck is dusted faintly with the same grit that's on the rest of {them}.",
        "{Their} throat works visibly as {they speak}, like a slightly mistuned instrument.",
        "A line of stubble runs unevenly down one side of {their} neck where the razor missed.",
    ],
    # =====================================================================
    # TORSO REGION — singular locations
    # =====================================================================
    "chest": [
        "{Their} chest rises and falls in slow, careful breaths.",
        "The outline of an old injury shows in the way {their} chest sits, uneven across the sternum.",
        ("slight", "{Their} chest holds the lean, slightly hollow build of long undereating."),
        ("stocky", "{Their} chest is broad and deep, and carries weight without strain."),
        "A faint persistent rattle accompanies {their} breath, audible only if one listens.",
        "{Their} chest shows the slight asymmetry of an old fracture badly healed.",
        "{Their} breathing is shallow, the breath of someone conserving energy or hiding pain.",
        ("stocky", "{Their} chest is barrel-shaped, the build of someone who has done their share of heavy work."),
        "{Their} chest carries a faint scar where a long surgical drain once sat.",
        ("slight", "{Their} chest is flat and small, the build of a sleeve that was probably underfed in development."),
        ("slight", "{Their} chest is narrow, with the prominent collarbones of a small frame."),
        "{Their} chest holds the slight forward curve of someone who hunches over their work.",
        "{Their} chest carries the slight asymmetry of an old break that healed at its own pace.",
        ("slight", "{Their} ribs press visibly against the skin on every inhale."),
        "There is a small, repeated motion in {their} chest, as if {they are} aware of their own heartbeat.",
        "{Their} chest moves smoothly, the easy mechanics of someone who has not yet been hit hard.",
        ("heavyset", "{Their} chest holds the rounded softness of someone who used to be heavier."),
        "{Their} chest bears a small port closure low under the collarbone, years old.",
        "{Their} chest is dusted faintly with the same colony grit that's everywhere else.",
        "{Their} breathing speeds up briefly when {they are} looked at, then settles again.",
        "{Their} chest is sweat-damp in a way that has nothing to do with the temperature.",
        "There's a small protrusion at the sternum — old break, badly set — that the eye finds.",
        "{Their} chest bears a long thin scar low across the sternum, old and pale.",
        "{Their} chest moves in time with an internal rhythm slightly off the room's.",
        "{Their} chest skin carries the small yellowed cast of long-term smoking.",
        ("lean", "{Their} chest holds the lean, hard build of someone who works for a living."),
        "{Their} chest skin bears the faint pale stripes where a harness has chronically pressed.",
        "{Their} chest looks deflated, as though {they have} not eaten properly in days.",
        "{Their} chest carries the slight forward roll of someone who works hunched over.",
        "There is a small, deliberate brand high on the upper chest, intentional and old.",
        ("heavyset", "{Their} chest holds the kind of soft barrel that comes from long, easy years."),
        "{Their} chest bears the faint old shadow of a tattoo that has been laser-faded.",
        "{Their} chest carries the small, deliberate scar of a port closure low at the sternum.",
        "{Their} breathing hitches very slightly on every third inhale, a tic {they have} stopped noticing.",
        "{Their} chest moves out of sync with the rest of {them}, breath fast while limbs are still.",
        ("athletic", "{Their} chest holds the slight pectoral broadness of someone whose work involves pulling."),
        "A thin pale scar runs vertically down the center of {their} sternum, surgical and old.",
        "{Their} chest carries a small puncture scar low on one side, the size of a finger.",
        "{Their} chest carries a healed surgical access scar low and to one side.",
        "{Their} chest holds the perfectly average build of someone genetically undistinguished.",
        "{Their} chest holds the slight slack of a sleeve well into middle years.",
    ],
    "back": [
        "{Their} back is hunched slightly, the cant of someone who has been bent over a workstation too long.",
        "A long, narrow scar runs diagonally across {their} upper back, the legacy of a single bad cut.",
        ("athletic", "{Their} back is broad enough to give them a slight wedge silhouette."),
        "{Their} posture suggests an old injury that has never been fully addressed.",
        "{Their} back is straight in a way that suggests training rather than nature.",
        "{Their} shoulders pull forward subtly, a chronic posture they no longer notice.",
        ("slight", "Bony shoulder blades stand out sharply, with every motion making them ripple."),
        ("heavyset", "{Their} back is wide and faintly soft, the build of someone settling into middle years."),
        "There's a permanent slight curve to {their} spine that suggests scoliosis.",
        "{Their} back rises and falls visibly with breaths that are deeper than they look from the front.",
        "A line of vertebrae stands out faintly down the center of {their} back.",
        "{Their} back is dotted with faint, faded freckles across the upper shoulders.",
        "{Their} shoulders are squared with the deliberate effort of someone who was told to stand straight.",
        "{Their} back is dusted faintly with what looks like ash or fine soot.",
        "{Their} spine sits visibly crooked, a misalignment that draws the eye.",
        "There's a strip of pale skin along the lower back where chronic pressure has worn the same line.",
        "{Their} back is held tense, shoulders close to the ears in a steady half-flinch.",
        "{Their} back shows the unmistakable pressure marks of body armor recently removed.",
        ("slight", "{Their} back is narrow, the build of someone who has stayed small on purpose."),
        "There's a healed knife scar low on the back, the kind that nicked but did not stop the lung.",
        "{Their} back moves with the loose, settled ease of someone with no immediate concerns.",
        "{Their} spine is rigidly straight, the bearing of someone who was trained to stand that way.",
        "{Their} back bears the faint outline of an old, large tattoo that runs from shoulder blade to shoulder blade.",
        "{Their} back curves into the chair or wall whenever there is something to lean against.",
        "{Their} shoulders roll slowly forward and back when {they think} no one is watching.",
        "{Their} back is faintly damp with sweat that has not yet had a chance to dry.",
        "There's a clear protrusion at the lower spine, the shape of an old impact that healed wrong.",
        "{Their} back is bare of any visible scars or marks, which itself feels noteworthy.",
        ("stocky", "{Their} back holds the broad, soft strength of someone who carries heavy things for a living."),
        "{Their} back bears the faint regular indentations of a chair {they have} spent too many hours in.",
        "There's a brand-shaped mark low on the back, healed but still raised against the skin.",
        "{Their} back hunches subtly forward whenever {they talk}, as if leaning into the conversation.",
        "{Their} back is straight enough to be slightly unnatural, the posture of professional bodyguards.",
        "{Their} shoulders carry the rolled-forward tension of someone whose neck hurts.",
        "{Their} back holds the slightly soft curve of someone whose work used to be physical and isn't anymore.",
        "{Their} back bears a constellation of small healed acne scars across the shoulders.",
        "There's a faint indentation between the shoulder blades that fingers want to find.",
        "{Their} back arches faintly with every deep breath, working out unseen tension.",
        "{Their} back wears the rumpled, slept-in cast of someone who passed out where they shouldn't have.",
        "{Their} back is faintly hairy at the shoulders, dense enough to catch the light.",
        "{Their} back bears a small faded brand between the shoulder blades.",
    ],
    "abdomen": [
        ("athletic", "{Their} abdomen is flat and tight, the build of someone who eats sparingly or works hard."),
        "{Their} stomach is faintly soft at the lower curve, in a way that suggests recent indulgence.",
        "{Their} abdomen carries the faint roundness of someone who has not been actively starving.",
        "A long, vertical scar runs down the center of {their} abdomen, the line of an old surgery.",
        "{Their} stomach moves visibly with each breath, sucked in and out.",
        ("heavyset", "{Their} belly carries a relaxed, generous roundness with cheerful indifference."),
        "{Their} abdomen is concave enough to suggest several missed meals.",
        "{Their} stomach holds the rounded weight of a person comfortable with food.",
        "{Their} abdomen carries the muscular ridges of someone who exercises with intent.",
        "A faded vertical scar low on the belly suggests an old appendectomy or similar.",
        "{Their} stomach bears a long-faded surgical scar to one side of the navel.",
        "{Their} belly trembles slightly with the high-strung tension of someone who has not eaten today.",
        "{Their} abdomen is dusted with the same grit that lives on the rest of {them}.",
        "{Their} stomach bears the small, regular punctures of insulin or stim injection sites.",
        "{Their} belly carries a small protrusion off-center that catches the eye.",
        "{Their} abdomen tightens visibly when {they are} addressed.",
        "{Their} stomach holds the slack of someone who used to be heavier and recently isn't.",
        "{Their} belly is taut, the small drum of someone who has not had a proper bowel movement in days.",
        "{Their} abdomen carries a tattoo that runs down toward the hip, illegible at this distance.",
        "{Their} stomach is faintly burned along one side, the legacy of a chemical splash long healed.",
        "{Their} belly is uneven, soft on one side and tight on the other.",
        "{Their} abdomen shows the small, regular scars of a chronic medical condition.",
        ("slight", "{Their} stomach is concave below the ribs in a way that draws the eye."),
        "{Their} belly bears the deep dimple of a navel piercing long since removed.",
        "{Their} abdomen is sleek with the kind of fitness that comes from regimented training.",
        "{Their} stomach growls faintly while {they stand}, the report of a long fast.",
        "{Their} belly is faintly distended, in a way that suggests a recent heavy meal.",
        "{Their} abdomen holds a faint sheen of sweat that catches the light unevenly.",
        "{Their} stomach bears a small healed knife scar just left of the navel.",
        "{Their} abdomen looks soft and untouched, the belly of someone who has never been hit hard.",
        "{Their} stomach carries the round shape of someone newly weight-trained.",
        ("athletic", "{Their} abdomen is taut and flat enough to suggest a recent weight cut."),
        ("heavyset", "{Their} belly hangs heavy in a soft, comfortable swell."),
        "{Their} stomach bears the broad horizontal line of an old C-section scar.",
        "{Their} abdomen sucks in tight whenever {they catch} a stranger's eye.",
        ("stocky", "{Their} belly is firm and round, the abdominal pressure of long-term beer drinking."),
        "{Their} abdomen bears a faded port closure just above the navel.",
        ("slight", "{Their} stomach is hollowed in a way that suggests both undereating and overworking."),
        "{Their} belly bears a smear of grease or something darker that {they have} not noticed.",
        "{Their} abdomen tightens and relaxes in a slow, deliberate rhythm — breathing exercises in public.",
        "{Their} belly bears a thin trail of dark hair running down from the navel.",
        "{Their} stomach sits in the slightly distended way that prolonged poor diet produces.",
    ],
    "groin": [
        "{Their} hips sit forward in the easy stance of someone who has nothing to protect.",
        "{Their} groin shows the chafed marks of gear worn too long against bare skin.",
        "{Their} hips hold an asymmetrical cant, one side higher than the other from old injury.",
        "{Their} groin is bandaged, the dressing grey at the edges.",
        ("slight", "{Their} hips sit too narrow to be the build's natural shape, the legacy of years of underfeeding."),
        "{Their} groin moves with the deliberate slowness of someone managing chronic discomfort.",
        ("athletic", "{Their} hips carry the broad set of someone built for endurance work."),
        "{Their} pelvis tilts slightly forward as {they stand}, throwing the back into a faint arch.",
        "{Their} groin area is dusted with the universal colony grit.",
        "{Their} hips bear the faint outline of a holstered sidearm that is not currently present.",
        "{Their} groin sits stiffly, the bearing of someone with a recent injury they are not discussing.",
        "{Their} hips are angled in the slight twist of someone whose pelvis was broken and reset.",
        "{Their} groin area carries the faint smell of antiseptic that lingers after recent treatment.",
        "{Their} hips sway very faintly when {they shift} weight, a small unconscious motion.",
        "{Their} groin sits well-aligned, the easy balance of someone whose body works.",
        "{Their} hips bear a small implant scar low along the iliac crest, healed pale.",
        "{Their} pelvis tilts back slightly, the posture of someone trying not to look too eager.",
        "{Their} groin is held stiffly forward, in a way that draws attention to itself.",
        "{Their} hips carry the slight forward swing of someone who has been on their feet too long.",
        "{Their} pelvis bears the faint raised outline of an old surgical site.",
        "{Their} groin area moves in time with {their} steps in the way of someone freshly out of physical therapy.",
        ("stocky", "{Their} hips are wide and steady, the structural foundation of a strong sleeve."),
        "{Their} pelvis sits in the faint forward thrust that comes from old back pain.",
        "{Their} groin carries the small dark spot of a port long since closed and faded.",
        "{Their} hips bear the bruise of a recent fall, fading yellow under the skin.",
        "{Their} pelvis holds itself with the slight protective curl of someone who has been kicked there recently.",
        "{Their} hips swing slightly when {they walk}, the gait of someone in no particular hurry.",
        "{Their} groin sits relaxed in the way of someone genuinely at ease.",
        "{Their} pelvis bears a small tattoo high on one side.",
        "{Their} hips carry the small tightness of someone fighting nerve pain.",
        "{Their} groin area is freshly washed, the cleanliness slightly out of step with the rest of {them}.",
        "{Their} hips sit square and stable, the bearing of a trained brawler.",
        "{Their} pelvis tilts forward into a chronic anterior tilt.",
        "{Their} groin bears the faint outline of a recent bandage adhesive square.",
        "{Their} hips bear silver-pale stretch marks high on either side.",
        "{Their} pelvis sits in the slightly torqued posture of someone with one leg slightly shorter than the other.",
        "{Their} groin area carries a faint chemical scent that suggests recent disinfectant exposure.",
        "{Their} hips bear the deep imprint of a holster belt worn for too many hours.",
        ("slight", "{Their} pelvis is small and narrow."),
        "{Their} groin carries the small old scar of a piercing site long since closed.",
        "{Their} hips bear the faint outline of armor that is no longer being worn.",
    ],
    # =====================================================================
    # PAIRED LOCATIONS — use pair-key entries
    # =====================================================================
    "eyes": [
        "{Their} {eyes} {are} an unremarkable brown that meet a stranger's gaze without comment.",
        "{Their} {eyes} {are} pale enough that the pupils stand out as sharp dark points.",
        "{Their} {eyes} {hold} the flat, careful neutrality of someone who has learned not to react.",
        "There's a faint redness at the rim of {their} {eyes} that suggests recent crying or recent stims.",
        "{Their} {eyes} {are} bright with the kind of alertness that comes from chemical assistance.",
        "{Their} {eyes} {sit} deep enough in {their} face to be perpetually shadowed.",
        "{Their} {eyes} {carry} the slow blink of someone in no particular hurry to focus.",
        "{Their} {eyes} {are} widely-spaced enough to give the face an open, slightly innocent look.",
        "{Their} {eyes} {are} close-set enough to make {them} look perpetually skeptical.",
        "{Their} {eyes} {are} dark to the point of looking almost black in the colony lighting.",
        "{Their} {eyes} {are} a startling pale grey that draws attention against the rest of the face.",
        "{Their} {eyes} {carry} the faint dilated quality of someone who has recently been in dim rooms.",
        "{Their} {eyes} {dart} toward sudden motion and then back, like a tic.",
        "{Their} {eyes} {hold} the steady, slightly out-of-focus look of someone listening to internal audio.",
        "A pale ring around {their} pupils suggests an optical implant in regular use.",
        "{Their} {eyes} {are} bloodshot enough to suggest a night without sleep.",
        "{Their} {eyes} {have} the slightly delayed blink of someone fighting fatigue.",
        "{Their} {eyes} {are} the same green-grey as old copper.",
        "{Their} {eyes} {are} a warm amber that catches the colony lights softly.",
        "{Their} {eyes} {hold} a faint perpetual squint that does not relax even in dim light.",
        "{Their} {eyes} {move} in small, precise saccades, scanning the room.",
        "There's a small flake of something pale caught at the corner of one eye.",
        "{Their} {eyes} {are} blue enough to be remarked on, in a face otherwise unremarkable.",
        "{Their} {eyes} {have} the slightly puffy quality of someone who slept very recently.",
        "{Their} {eyes} {carry} the deliberate stillness of someone who has trained {themselves} not to glance away.",
        "{Their} {eyes} {are} an unmatched pair — one slightly lighter than the other.",
        "{Their} {eyes} {sit} slightly asymmetrically, one higher than the other.",
        "{Their} {eyes} {hold} the faint wet sheen of someone fighting the urge to blink.",
        "{Their} {eyes} {are} framed by lashes thick enough to cast small shadows on the cheeks.",
        "{Their} {eyes} {carry} a thin film of moisture that catches the light.",
        "{Their} {eyes} {are} sharply defined by deep set crows-feet at the corners.",
        "{Their} {eyes} {have} the bright dilated quality of someone running on adrenaline.",
        "{Their} {eyes} {are} a soft hazel that shifts toward green in the colony lighting.",
        "{Their} {eyes} {hold} the perpetually-wet quality of allergies or grief or both.",
        "{Their} {eyes} {have} the matte quality of cataracts beginning to form.",
        "{Their} {eyes} {hold} the small ironic glint of someone who finds most of this funny.",
        "{Their} {eyes} {dart} over the room without seeming to see any of it.",
        "{Their} {eyes} {hold} steady on whatever they look at, with a quality that strangers find uncomfortable.",
        "{Their} {eyes} {are} slightly yellowed in the whites, the legacy of a chronic condition.",
        "{Their} {eyes} {carry} the slight glassiness of recent intoxication.",
        "{Their} {eyes} {hold} a faint reflective ring of an active optic implant.",
        "{Their} {eyes} {are} a striking violet that the lighting cannot quite explain.",
    ],
    "ears": [
        "{Their} {ears} {are} small and tight against the skull, faintly translucent at the edges.",
        "{Their} {ears} {carry} the faint flush of cold or embarrassment.",
        "{Their} {ears} {bear} small clean piercing holes through the lobes, currently empty.",
        "{Their} {ears} {are} larger than the rest of the face would suggest.",
        "There's a faint healed split along the lobe of {their} {ears} where piercings used to be.",
        "{Their} {ears} {bear} the small, hard scar tissue of someone who has had cauliflower ear treated.",
        "{Their} {ears} {sit} asymmetrically against the head, one slightly higher than the other.",
        "{Their} {ears} {are} pierced multiple times along the cartilage, the holes mostly empty now.",
        "{Their} {ears} {bear} faint pale outlines where headphones or comms gear has rested for years.",
        "A small data port nestles behind the curve of {their} {ears}.",
        "{Their} {ears} {carry} the small flake-edges of dry skin that won't quite resolve.",
        "{Their} {ears} {bear} a single matched pair of healed lobe piercings, modest and uniform.",
        "{Their} {ears} {stick} out from the head at a slight angle, giving {them} a faintly alert look.",
        "{Their} {ears} {are} flushed pink at the rim, the colony temperature notwithstanding.",
        "{Their} {ears} {have} the slightly torn-and-healed look of long-ago bar fights.",
        "{Their} {ears} {carry} small healed scars along the cartilage where someone bit or struck them.",
        "{Their} {ears} {are} tipped with the faint hair of a sleeve that grows facial hair early.",
        "{Their} {ears} {bear} the indentation of recent headphone use.",
        "{Their} {ears} {are} sleek and small, set close to a narrow skull.",
        "{Their} {ears} {bear} a row of tiny stud holes along the cartilage, abandoned.",
        "{Their} {ears} {carry} the faint sheen of a recently-cleaned hearing implant.",
        "{Their} {ears} {bear} the small protrusion of an under-skin earpiece.",
        "{Their} {ears} {are} reddened from cold despite the controlled colony temperature.",
        "{Their} {ears} {bear} faint healed holes where piercings once sat, now closed over.",
        "There's a small dark mole on the lobe of one ear that draws the eye.",
        "{Their} {ears} {carry} the visible scar of an old surgical access behind the lobe.",
        "{Their} {ears} {are} framed by hair just long enough to half-conceal them.",
        "{Their} {ears} {bear} heavily stretched lobes from long-term gauge wear, currently empty.",
        "{Their} {ears} {sit} close enough to the skull to be easily missed.",
        "{Their} {ears} {bear} a single piercing each, healed long ago and now bare.",
        "{Their} {ears} {turn} faintly when there's an unexpected sound, like an animal's.",
        "{Their} {ears} {are} clean and uncluttered, in a way that suggests deliberate grooming.",
        "{Their} {ears} {bear} a small healed nick on the lobe of each, faded white.",
        "{Their} {ears} {carry} the soft fine hair of a sleeve newly emerged from the tank.",
        "{Their} {ears} {have} a faint asymmetry, one rounder and one more pointed.",
        "{Their} {ears} {bear} the faint pucker of healed frostbite damage.",
        "{Their} {ears} {carry} small, almost invisible implant studs, visible only on close look.",
        "{Their} {ears} {bear} the small bumps of old keloid scars from previous piercings.",
        "{Their} {ears} {carry} the slightly cauliflowered thickening of someone who used to fight regularly.",
        "{Their} {ears} {are} remarkably small, almost vestigial-looking against the head.",
        "{Their} {ears} {bear} a single tiny piercing high on the cartilage of each side.",
        "{Their} {ears} {are} perpetually a shade redder than the rest of the face.",
    ],
    "arms": [
        "Old ink has spread under the skin here, the lines blurred past reading.",
        "A constellation of small round burn marks runs up the inside of one forearm.",
        "Small healed punctures mark the crook of each elbow, in a pattern that rotates.",
        "Fine pale hair catches the colony light along the outside.",
        "Grease has gone into the creases and stayed there.",
        "{Their} {arms} {hang} loose at {their} sides, ending in hands that are never quite still.",
        "Veins stand close to the surface, visible without effort.",
        "A deep scar crosses one bicep, long healed and badly closed.",
        "Small dark moles scatter across the shoulders.",
        "Silver grooves run along the inside of one forearm, old enough to have stopped meaning anything to anyone but {them}.",
        "The skin is chafed in a band where a harness has ridden too many times.",
        "A single old tattoo sits at the inner forearm — a date, a name, illegible at this distance.",
        "Freckles crowd the inner forearm and thin out toward the wrist.",
        "{Their} {arms} {hold} a slight tremor at rest, faint but constant.",
        "Scratches cross the forearms, the small marks of working in tight spaces.",
        "Ink runs shoulder to wrist, dense enough that the skin between is hard to find.",
        "A pale mark the shape of a hand-grip has faded into one forearm.",
        "The tan stops in a hard line above the elbow.",
        "Neat surgical scars sit at both shoulders, the tidy signature of chrome going in.",
        "{Their} {arms} {carry} a sheen of dried sweat in patches.",
        "Small flat moles speckle the skin, the kind long sun leaves behind.",
        ("slight", "Narrow through the wrist, and narrow enough that the bones show."),
        ("slight", "{Their} {arms} {are} slender to the point of looking fragile."),
        ("lean", "{Their} {arms} {are} corded with the lean muscle of somebody whose work is physical."),
        ("lean", "Wiry — the muscle that comes from hauling rather than lifting."),
        ("athletic", "{Their} {arms} {are} heavy with muscle and dotted with small healed cuts."),
        ("athletic", "Deep callus sits where a tool is gripped, and the forearm is built around it."),
        ("average", "{Their} {arms} {are} unremarkable — neither trained nor wasted."),
        ("stocky", "Thick through the forearm, with the blunt strength of somebody who lifts for a living."),
        ("heavyset", "{Their} {arms} {are} heavy with a sleeper's softness, untrained but solid."),
        ("heavyset", "Soft through the upper arm, in a way the rest of {them} does not contradict."),
    ],
    "hands": [
        "Deep callus has built across the palms, harder than the fingers.",
        "The nails are bitten down to the quick.",
        "Small healed cuts cross the knuckles, too regular to be accidents.",
        "Something dark has settled around the nail beds — ink, grease, or worse.",
        "Veins track prominently across the backs.",
        "Small tattoos sit on the knuckles — letters, perhaps, or symbols.",
        "Pale bands mark every finger but the thumbs, where rings have habitually sat.",
        "Nicks cover the backs, the small toll of cheap tools.",
        "Small dark moles scatter across the backs.",
        "The calluses have cracked open where gloves stopped protecting years ago.",
        "A fine tremor moves through them, constant and unhidden.",
        "Two fingers set crooked, broken once and never properly straightened.",
        "The nails are dyed faintly orange — nicotine, or hair colour, hard to say.",
        "{Their} {hands} {carry} the careful stillness of somebody fighting a tremor.",
        "Scars cross the palms in the pattern broken glass leaves.",
        "{Their} {hands} {are} crossed in front of {them}, a small habitual gesture.",
        "Machine grime has worked into the knuckle creases.",
        "The index and middle fingers have yellowed with years of smoke.",
        "{Their} {hands} {are} unusually clean, in a way that draws notice in a place like this.",
        "{Their} {hands} {are} folded loosely, the posture of somebody who is not threatened.",
        "The skin is dry and papery, the way it goes when chemicals are part of the work.",
        "Neat implant scars sit in the palms.",
        "A pale band crosses one wrist where a device used to sit.",
        "Rope has worn its own calluses in a line across the fingers.",
        "The fingers work at each other, as though to stop them doing something else.",
        ("slight", "Narrow through the back, the tendons standing clear."),
        ("lean", "Long-fingered and spare, with very little padding anywhere."),
        ("athletic", "The knuckles are broad, and have been broadened."),
        ("average", "{Their} {hands} {are} ordinary — some old scars, some fresh nicks, nothing that tells a story."),
        ("stocky", "{Their} {hands} {are} large and broad, the fingers thick at the joints."),
        ("heavyset", "Soft and heavy, with dimples where the knuckles should stand out."),
        ("heavyset", "{Their} {hands} {are} soft and clean, in a way that suggests {they have} never worked with them."),
    ],
    "thighs": [
        "Colony grit has worked into the skin here and stopped washing out.",
        "A tattoo sits on the outside, faded so far past legibility that only {they could} say what it was.",
        "Silver stretch marks fan across the outer curve, old enough to have gone pale.",
        "There's a sharp line across the upper thigh where sun stopped and covered skin began.",
        "A holster has pressed its outline high on the inside, one shift at a time, for years.",
        "The skin is smooth and hairless in a way that is clearly a decision.",
        "Grooming stopped being a priority here some months ago.",
        "Small faded marks record years of bumping past hard edges in narrow corridors.",
        "One knee turns inward a little when {they stand} at rest.",
        "{They cross} {their} {thighs} habitually when standing, knees touching.",
        "The skin here is paler than the rest of {them}, and newer.",
        "Something the size of a coin was taken off here once; the mark stayed.",
        "A knife sheath has worn a shallow patch against the bare skin.",
        "{Their} {thighs} {carry} the deep ache of long shifts spent standing on hard flooring.",
        "There is a scattering of small pale scars, none of them recent enough to matter.",
        "A faint tremor moves through the muscle when {they have} been on {their} feet too long.",
        "The left sits a fraction differently from the right, and always has.",
        "Fine hair lies flat along the outside, catching the light in one direction only.",
        "A pale seam runs high on one side, thin and long since closed.",
        "{Their} {thighs} {are} unremarkable, and {they have} never once thought about them.",
        "Warmth comes off them the way it does off somebody who has been walking fast.",
        ("slight", "The bones of the iliac crest stand sharply above them."),
        ("slight", "There is very little here — the long, spare legs of somebody the colony has not been generous to."),
        ("lean", "{Their} {thighs} {carry} the stringy, unhurried strength of somebody whose work is mostly walking."),
        ("lean", "Narrow, and narrow enough that the difference between the two of them is easy to see."),
        ("athletic", "Muscle stands out clean along the front when {they shift} {their} weight."),
        ("athletic", "{Their} {thighs} {carry} the dense, deliberate build of regular squatting."),
        ("athletic", "The long definition of somebody who runs, and runs to be alone rather than to be fast."),
        ("stocky", "Heavy and solid, the legs of somebody who covers distance on foot every day of their life."),
        ("heavyset", "{Their} {thighs} {are} heavy with a soft weight that used to be muscle."),
        ("heavyset", "Full and soft, and they touch when {they stand}."),
        ("average", "Neither strong nor soft — legs that do what is asked and nothing more."),
    ],
    "shins": [
        "Small faded marks record years of walking into things in the dark.",
        "Fine dark hair lies in a wiry pattern down the front.",
        "The bone runs close under the skin, unpadded.",
        "A pale line follows the bone, old enough to be a memory.",
        "Dust has settled into the skin and stopped coming out.",
        "The skin is dry and flaking along the front.",
        "A dent sits in the bone where an old blow didn't quite break it.",
        "A permanent ring above the ankle marks where something has been worn tight for years.",
        "The tan stops in a hard line partway down.",
        "Old grazes have healed pale and scattered.",
        "{Their} {shins} {are} bare of any mark worth reading, surprisingly clean for a sleeve this used.",
        "Bruises come and go here faster than they heal.",
        "A tattoo runs down one side, the ink gone soft at the edges.",
        "The skin shines faintly where hair no longer grows.",
        "{Their} {shins} {carry} the dull ache of somebody who stands for a living.",
        "The ankles are thicker at the end of a shift than the start.",
        "Pale climbing marks run along the bone.",
        "A cold-weather mottle patterns the skin, red and white.",
        "{They shift} {their} weight often, as though standing still costs something.",
        "Grit is worked into a scrape that has not finished closing.",
        ("slight", "Thin enough that the bone is the widest part."),
        ("slight", "{Their} {shins} {are} narrow, with almost nothing over the bone."),
        ("lean", "Long and spare, the calf sitting high."),
        ("athletic", "The calf is defined enough to show its separation when {they stand}."),
        ("athletic", "{Their} {shins} {carry} the built-up muscle of somebody who covers ground on foot."),
        ("average", "Ordinary legs that have been walked on, and not much more."),
        ("stocky", "Thick through the calf, and solid all the way down."),
        ("heavyset", "{Their} {shins} {are} heavy, the ankle thickening where it meets the foot."),
        ("heavyset", "Full through the calf, the skin stretched smooth over it."),
    ],
    "feet": [
        "The soles are thick with callus, worst at the heel.",
        "The nails are cut short and unevenly.",
        "A pale mark crosses the top where the sun has never reached.",
        "The second toe is longer than the first.",
        "Grime has settled between the toes and stayed.",
        "The little toe sits tucked under its neighbour, pushed there years ago.",
        "{Their} {feet} {are} splayed slightly, the arch long since flattened.",
        "A bunion pushes out at the base of the big toe.",
        "The heels are cracked deep enough to have stopped hurting.",
        "Old blisters have healed into hard pale patches.",
        "{They shift} {their} weight from one foot to the other without noticing.",
        "The skin is soft and pale, unused to going bare.",
        "A toenail has gone thick and yellow and been left to it.",
        "Fine dark hair grows across the tops of the toes.",
        "The arch is high enough to leave a broken print.",
        "Dust has worked into every crease.",
        "{Their} {feet} {carry} the ache of a shift that ran long.",
        "One turns outward when {they stand} at rest.",
        "A scar crosses the top, straight and deliberate-looking.",
        "The ankle bone is knobbed and prominent.",
        "The skin is stained faintly where cheap dye has run.",
        "A small tattoo sits on the top, private and easily missed.",
        ("slight", "Narrow, with the tendons standing up under the skin."),
        ("lean", "Long and thin, the toes spread wide."),
        ("athletic", "{Their} {feet} {are} broad through the ball, built for pushing off."),
        ("average", "Ordinary — neither pretty nor punished."),
        ("stocky", "Broad and flat, the toes short and square."),
        ("heavyset", "{Their} {feet} {are} wide, the flesh spreading where it meets the floor."),
        ("heavyset", "Puffed slightly at the ankle, with a pressed line where something has been worn tight."),
    ],
}
