# Generated by Django 6.0.2 on 2026-03-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KeywordEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("custom_set", "Custom Keyword Set"),
                            ("admin_add", "Admin Added to Approved List"),
                            ("admin_remove", "Admin Removed from Approved List"),
                        ],
                        db_index=True,
                        help_text="The kind of keyword event.",
                        max_length=20,
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        db_index=True,
                        help_text="The keyword string that was set, added, or removed.",
                        max_length=20,
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Character key at the time of the event (for custom_set).",
                        max_length=80,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Account key for attribution.",
                        max_length=80,
                    ),
                ),
                (
                    "gender_list",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "N/A"),
                            ("feminine", "Feminine"),
                            ("masculine", "Masculine"),
                            ("neutral", "Neutral"),
                        ],
                        default="",
                        help_text="Which gender list (for admin_add / admin_remove).",
                        max_length=10,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the event occurred.",
                    ),
                ),
            ],
            options={
                "verbose_name": "keyword event",
                "verbose_name_plural": "keyword events",
                "ordering": ["-timestamp"],
            },
        ),
    ]
